from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors

INCH_TO_PT = 72.0
MM_TO_PT = INCH_TO_PT / 25.4


def inch(value: float) -> float:
    return value * INCH_TO_PT


def mm(value: float) -> float:
    return value * MM_TO_PT


REPO_ROOT = Path(__file__).resolve().parents[2]
ASSETS_DIR = REPO_ROOT / "assets"
FONTS_DIR = ASSETS_DIR / "fonts"

ANDIKA_REGULAR_TTF = FONTS_DIR / "Andika-Regular.ttf"
ANDIKA_BOLD_TTF = FONTS_DIR / "Andika-Bold.ttf"

FONT_REGULAR_NAME = "Andika"
FONT_BOLD_NAME = "Andika-Bold"
FALLBACK_FONT_REGULAR = "Helvetica"
FALLBACK_FONT_BOLD = "Helvetica-Bold"

PAGE_WIDTH_PT = inch(8.5)
PAGE_HEIGHT_PT = inch(11.0)

MARGIN_LEFT_PT = inch(0.6)
MARGIN_RIGHT_PT = inch(0.6)
MARGIN_TOP_PT = inch(0.5)
MARGIN_BOTTOM_PT = inch(0.5)

CONTENT_WIDTH_PT = PAGE_WIDTH_PT - MARGIN_LEFT_PT - MARGIN_RIGHT_PT
CONTENT_HEIGHT_PT = PAGE_HEIGHT_PT - MARGIN_TOP_PT - MARGIN_BOTTOM_PT

GUIDE_WIDTH_PT = inch(6.8)
GUIDE_MAIN_HEIGHT_PT = mm(15.0)
GUIDE_DESC_RATIO = 0.45
GUIDE_DESC_HEIGHT_PT = GUIDE_MAIN_HEIGHT_PT * GUIDE_DESC_RATIO
GUIDE_PAD_TOP_PT = mm(2.0)
GUIDE_ROW_HEIGHT_PT = GUIDE_DESC_HEIGHT_PT + GUIDE_MAIN_HEIGHT_PT + GUIDE_PAD_TOP_PT
GUIDE_BASELINE_STROKE_PT = 1.0
GUIDE_TOPLINE_STROKE_PT = 1.0
GUIDE_MIDLINE_STROKE_PT = 0.8
GUIDE_MIDLINE_DASH_ON_PT = 3.0
GUIDE_MIDLINE_DASH_OFF_PT = 3.0
GUIDE_TEXT_X_OFFSET_PT = 4.0
GUIDE_DRAW_TOPLINE = True
MIDLINE_RATIO = 0.5

TITLE_SIZE_PT = 16.0
BODY_SIZE_PT = 11.0
SENTENCE_DISPLAY_SIZE_PT = 14.0
#0.96 for “bigger but safe”
#0.98 for “tight / near-max”
MODEL_TEXT_SAFETY = 0.97
FONT_EM_UNITS = 1000.0

HEADER_TITLE_GAP_PT = 6.0
HEADER_LINE_GAP_PT = 4.0
HEADER_BLOCK_GAP_PT = 8.0

EMOTION_PROMPT_GAP_PT = 12.0
EMOTION_CIRCLE_RADIUS_PT = 6.0
EMOTION_CIRCLE_CENTER_OFFSET_PT = 3.0
EMOTION_LABEL_GAP_PT = 6.0
EMOTION_CHOICE_GAP_PT = 12.0
EMOTION_CIRCLE_STROKE_PT = 1.0
EMOTION_CIRCLE_DIAMETER_PT = EMOTION_CIRCLE_RADIUS_PT * 2.0

REMINDER_BOX_PADDING_PT = 6.0
REMINDER_TITLE_GAP_PT = 4.0
REMINDER_LINE_GAP_PT = 3.0
REMINDER_BORDER_STROKE_PT = 1.0

SENTENCE_LABEL_GAP_PT = 4.0
SECTION_TITLE_GAP_PT = 6.0

TRACE_ROW_GAP_PT = 6.0
TRACE_TO_WRITE_GAP_PT = 8.0
WRITE_ROW_GAP_MIDLINE_PT = 6.0
WRITE_ROW_GAP_NO_MIDLINE_PT = 8.0
SECTION_GAP_PT = 10.0

CARTOON_MAX_W_IN = 1.5
CARTOON_MAX_H_IN = 1.5
CARTOON_MAX_W_PT = inch(CARTOON_MAX_W_IN)
CARTOON_MAX_H_PT = inch(CARTOON_MAX_H_IN)
CARTOON_PAD_PT = mm(6.0)
CARTOON_PLACEHOLDER_STROKE_PT = 1.0

MODEL_TEXT_COLOR = colors.Color(0.75, 0.75, 0.75)
MIDLINE_COLOR = colors.grey
PRIMARY_LINE_COLOR = colors.black
TEXT_COLOR = colors.black

PDF_AUTHOR = "worksheet-gen"
PDF_SUBJECT = "handwriting practice"

DEFAULT_TITLE_EN = "Abby’s Handwriting Practice – English"
DEFAULT_TITLE_FR = "Pratique d’écriture – Français"
DEFAULT_DATE_EN = "Date: ____________________"
DEFAULT_DATE_FR = "Date : ____________________"
DEFAULT_EMOTION_TEXT_EN = "How does this feel today?"
DEFAULT_EMOTION_CHOICES_EN = ["Happy", "Okay", "Hard"]
DEFAULT_REMINDER_TITLE_EN = "Remember:"
DEFAULT_REMINDER_B_LINE_EN = "b = stick first, then circle (ball)"
DEFAULT_REMINDER_D_LINE_EN = "d = circle first, then stick (dog)"
DEFAULT_SENTENCE_DISPLAY_EN = "Abby bakes bread."
DEFAULT_SENTENCE_MODEL_EN = "Abby bakes bread."
DEFAULT_CHILD_NAME_PLACEHOLDER = "____________________"
